FROM alpine
MAINTAINER Andrew Taranik

RUN apk add --update python py-pip py-crypto py-psutil \
 && pip install --upgrade pip virtualenv  \
 && virtualenv  --system-site-packages /cloudify \
 && source /cloudify/bin/activate \
 && pip install cloudify \
 && pip install ConfigObj diamond cloudify-diamond-plugin \
 && pip install https://github.com/cloudify-cosmo/cloudify-aws-plugin/archive/1.4.zip \
 && rm -rf /var/cache/apk/* \
 && rm -rf ~/.cache \
 && echo -e "#!/bin/sh\nsource /cloudify/bin/activate && cfy \$*" >/bin/run_cfy \
 && chmod +x /bin/run_cfy

RUN mkdir -p /cfy
WORKDIR /cfy
VOLUME /cfy

#ENTRYPOINT ["run_cfy"]
#CMD ["-h"]
CMD run_cfy --version
